"""
Villa Guest Message Classifier — BERT Training Pipeline
=========================================================
Model  : distilbert-base-uncased  (fast, lightweight, excellent for short texts)
Task   : Multi-class text classification (6 categories) + sentiment score
Dataset: train.csv / val.csv / test.csv  (generated by generate_dataset.py)

Usage:
  # 1. Install deps
  pip install transformers torch datasets scikit-learn pandas accelerate

  # 2. Train
  python bert_trainer.py --train

  # 3. Evaluate on test set
  python bert_trainer.py --evaluate

  # 4. Run inference on a single message
  python bert_trainer.py --predict "The AC is broken and no one is helping us!"
"""

import argparse
import json
import os
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import classification_report, confusion_matrix
from torch.utils.data import Dataset
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)

# ── Config ─────────────────────────────────────────────────────────────────────

BASE_MODEL   = "distilbert-base-uncased"
OUTPUT_DIR   = "./villa_bert_model"
DATA_DIR     = "."                           # folder containing train/val/test CSVs
MAX_LENGTH   = 128                           # villa messages are short
BATCH_SIZE   = 16
EPOCHS       = 5
LEARNING_RATE = 2e-5
WARMUP_RATIO  = 0.1
WEIGHT_DECAY  = 0.01

CATEGORIES = [
    "pre_sales_availability",
    "pre_sales_pricing",
    "post_sales_checkin",
    "special_request",
    "complaint",
    "general_enquiry",
]
LABEL2ID = {cat: i for i, cat in enumerate(CATEGORIES)}
ID2LABEL = {i: cat for cat, i in LABEL2ID.items()}

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

# ── Dataset ────────────────────────────────────────────────────────────────────

class GuestMessageDataset(Dataset):
    def __init__(self, csv_path: str, tokenizer, max_length: int = MAX_LENGTH):
        self.df        = pd.read_csv(csv_path)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row     = self.df.iloc[idx]
        message = str(row["message"])
        label   = int(row["label"])

        encoding = self.tokenizer(
            message,
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids":      encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels":         torch.tensor(label, dtype=torch.long),
        }


# ── Metrics ────────────────────────────────────────────────────────────────────

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc   = (preds == labels).mean()
    return {"accuracy": acc}


# ── Training ───────────────────────────────────────────────────────────────────

def train():
    print("\n=== Loading tokenizer and model ===")
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
    model     = AutoModelForSequenceClassification.from_pretrained(
        BASE_MODEL,
        num_labels=len(CATEGORIES),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )

    print("=== Loading datasets ===")
    train_ds = GuestMessageDataset(f"{DATA_DIR}/train.csv", tokenizer)
    val_ds   = GuestMessageDataset(f"{DATA_DIR}/val.csv",   tokenizer)
    print(f"  Train: {len(train_ds)} | Val: {len(val_ds)}")

    training_args = TrainingArguments(
        output_dir                  = OUTPUT_DIR,
        num_train_epochs            = EPOCHS,
        per_device_train_batch_size = BATCH_SIZE,
        per_device_eval_batch_size  = BATCH_SIZE,
        learning_rate               = LEARNING_RATE,
        warmup_ratio                = WARMUP_RATIO,
        weight_decay                = WEIGHT_DECAY,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        load_best_model_at_end      = True,
        metric_for_best_model       = "accuracy",
        greater_is_better           = True,
        logging_dir                 = f"{OUTPUT_DIR}/logs",
        logging_steps               = 20,
        report_to                   = "none",          # disable wandb/mlflow
        fp16                        = torch.cuda.is_available(),
    )

    trainer = Trainer(
        model           = model,
        args            = training_args,
        train_dataset   = train_ds,
        eval_dataset    = val_ds,
        compute_metrics = compute_metrics,
        callbacks       = [EarlyStoppingCallback(early_stopping_patience=2)],
    )

    print("\n=== Training ===")
    trainer.train()

    print(f"\n=== Saving best model to {OUTPUT_DIR} ===")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    # Save label map alongside model
    with open(f"{OUTPUT_DIR}/label_map.json", "w") as f:
        json.dump({"label2id": LABEL2ID, "id2label": ID2LABEL}, f, indent=2)

    print("Done! Model saved.")


# ── Evaluation ─────────────────────────────────────────────────────────────────

def evaluate():
    print("\n=== Loading trained model ===")
    tokenizer = AutoTokenizer.from_pretrained(OUTPUT_DIR)
    model     = AutoModelForSequenceClassification.from_pretrained(OUTPUT_DIR).to(DEVICE)
    model.eval()

    print("=== Loading test set ===")
    test_ds = GuestMessageDataset(f"{DATA_DIR}/test.csv", tokenizer)
    df_test = pd.read_csv(f"{DATA_DIR}/test.csv")

    all_preds, all_labels = [], []
    loader = torch.utils.data.DataLoader(test_ds, batch_size=BATCH_SIZE)

    with torch.no_grad():
        for batch in loader:
            input_ids      = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            labels         = batch["labels"]

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            preds   = torch.argmax(outputs.logits, dim=-1).cpu().numpy()

            all_preds.extend(preds)
            all_labels.extend(labels.numpy())

    print("\n=== Classification Report ===")
    print(classification_report(
        all_labels, all_preds,
        target_names=CATEGORIES,
        digits=3,
    ))

    print("=== Confusion Matrix ===")
    cm = confusion_matrix(all_labels, all_preds)
    cm_df = pd.DataFrame(cm, index=CATEGORIES, columns=CATEGORIES)
    print(cm_df.to_string())

    # Save results
    df_test["predicted_category"] = [ID2LABEL[p] for p in all_preds]
    df_test["correct"] = df_test["label"] == [l for l in all_preds]
    df_test.to_csv(f"{OUTPUT_DIR}/test_predictions.csv", index=False)
    print(f"\nPredictions saved to {OUTPUT_DIR}/test_predictions.csv")


# ── Inference ──────────────────────────────────────────────────────────────────

class VillaMessageClassifier:
    """
    Lightweight inference wrapper — use this in your FastAPI app.

    Example:
        from bert_trainer import VillaMessageClassifier
        classifier = VillaMessageClassifier()
        result = classifier.predict("The AC is broken!")
    """

    def __init__(self, model_dir: str = OUTPUT_DIR):
        self.tokenizer = AutoTokenizer.from_pretrained(model_dir)
        self.model     = AutoModelForSequenceClassification.from_pretrained(model_dir).to(DEVICE)
        self.model.eval()

    def predict(self, message: str) -> dict:
        inputs = self.tokenizer(
            message,
            max_length=MAX_LENGTH,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        ).to(DEVICE)

        with torch.no_grad():
            outputs = self.model(**inputs)
            logits  = outputs.logits[0]
            probs   = torch.softmax(logits, dim=-1)

        pred_id    = torch.argmax(probs).item()
        confidence = probs[pred_id].item()

        # All category probabilities
        all_probs = {
            ID2LABEL[i]: round(p.item(), 4)
            for i, p in enumerate(probs)
        }

        return {
            "category":       ID2LABEL[pred_id],
            "confidence":     round(confidence, 4),
            "all_probs":      all_probs,
        }


def predict_single(message: str):
    classifier = VillaMessageClassifier()
    result     = classifier.predict(message)

    print(f"\nMessage   : {message}")
    print(f"Category  : {result['category']}")
    print(f"Confidence: {result['confidence']:.1%}")
    print("\nAll probabilities:")
    for cat, prob in sorted(result["all_probs"].items(), key=lambda x: -x[1]):
        bar = "█" * int(prob * 30)
        print(f"  {cat:<28} {prob:.4f}  {bar}")


# ── CLI ────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Villa BERT Classifier")
    parser.add_argument("--train",    action="store_true", help="Train the model")
    parser.add_argument("--evaluate", action="store_true", help="Evaluate on test set")
    parser.add_argument("--predict",  type=str,            help="Predict a single message")
    args = parser.parse_args()

    if args.train:
        train()
    elif args.evaluate:
        evaluate()
    elif args.predict:
        predict_single(args.predict)
    else:
        parser.print_help()
